---
  instance_name:
    description: "Instance name, provided by ServiceNow"
    type: "string"
    secret: false
    required: true
  username:
    description: "Username for the servicenow account"
    type: "string"
    required: true
  password:
    description: "Password for the servicenow account"
    type: "string"
    secret: true
    required: true
  custom_params:
    description: "ServiceNow options that will be passed to all requests"
    type: object
    required: false
  use_new_service_now_api:
    description: "Use the new ServiceNow APIs to avoid deprecation warnings."
    type: "boolean"
    secret: false
    required: false
    default: true
